# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo
from Funcs import getTests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.tests = getTests()
        colors_num = getinfo()[0]

        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)

        #menu
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet(f"background-color: {colors[colors_num][5]};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton.setIcon(QtGui.QIcon(f"..\\pics\\mainpic{colors[colors_num][7]}.png"))
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet(f"background-color: {colors[colors_num][4]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_3.setIcon(QtGui.QIcon(f"..\\pics\\settingsico{colors[colors_num][7]}.png"))
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.pushButton_update = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_update.setIcon(QtGui.QIcon(f"..\\pics\\updating{colors[colors_num][7]}.png"))
        self.pushButton_update.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_update.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_update.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_update.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_update.setText("")
        self.pushButton_update.setObjectName("pushButton_update")
        self.verticalLayout.addWidget(self.pushButton_update)

        self.horizontalLayout.addWidget(self.frame)

        #tests
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setSpacing(20)
        self.gridLayout.setContentsMargins(17, 10, 15, 10)

        count = len(self.tests)
        self.Tests = []
        number = 0
        i = 0
        j = 0
        for i in range(count):
                number = i

                if number < count:
                        with open("tests/" + self.tests[number]) as f:
                                test = eval(f.read())

                if j == 4:
                      break
                i = i % 8
                frame_3 = MyFrame(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border-radius: 5px;", self.gridFrame)
                frame_3.setMinimumSize(QtCore.QSize(125, 200))
                frame_3.setMaximumSize(QtCore.QSize(125, 200))
                frame_3.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
        "border-radius: 5px;")
                frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                frame_3.setObjectName("frame_3")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(frame_3)
                self.verticalLayout_3.setObjectName("verticalLayout_2")

                pixmap = QtGui.QPixmap(f'testsimgs\\{test["iconame"]}.png')
                label = QtWidgets.QLabel()
                label.setPixmap(pixmap)
                label.setAlignment(QtCore.Qt.AlignCenter)
                self.verticalLayout_3.addWidget(label)
                
                self.textBrowser_2 = MyTextBrowser(frame_3)
                self.textBrowser_2.setObjectName("textBrowser")
                self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
                for l in test["Name"].split("\n"):
                        self.textBrowser_2.append(l)
                self.textBrowser_2.setStyleSheet(f'color:{colors[colors_num][6]}; font: 63 14px "Yu Gothic UI Semibold";')
                self.verticalLayout_3.addWidget(self.textBrowser_2)
                
                self.gridLayout.addWidget(frame_3, j, 0 + i, 1, 1)

                if i % 7 == 0 and i != 0:
                      j += 1

                self.Tests.append(frame_3)

        if number < 6:
                spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.gridLayout.addItem(spacerItem1, j, i + 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, j + 1, 0, 1, 1)

        self.horizontalLayout.addWidget(self.gridFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
