# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors, colors_editor
from mysettings import getinfo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        colors_num, ip, port, colors_num_editor = getinfo()

        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)


        #menu
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet(f"background-color: {colors[colors_num][5]};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton.setIcon(QtGui.QIcon(f"..\\pics\\mainpic{colors[colors_num][7]}.png"))
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_3.setIcon(QtGui.QIcon(f"..\\pics\\settingsico{colors[colors_num][7]}.png"))
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.horizontalLayout.addWidget(self.frame)
        
        
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_3.addItem(spacerItem1)
        
        self.gridFrame = QtWidgets.QFrame(self.verticalFrame)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridFrame)
        self.label.setStyleSheet(f"color:{colors[colors_num][6]};\n"
"font: 63 12pt \\\"Yu Gothic UI Semibold\\\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridFrame)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setStyleSheet("background: #fff;\n"
f"color:#000;\n"
"font: 8pt \"Arial\";\n"
"border-radius: 2px;\n"
"border: 0px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(colors[colors_num][8])
        for key, value in colors.items():
                if key != colors_num:
                        self.comboBox.addItem(value[8])
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame)
        self.label_4.setStyleSheet(f"color:{colors[colors_num][6]};\n"
"font: 63 12pt \\\"Yu Gothic UI Semibold\\\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.comboBox_editor = QtWidgets.QComboBox(self.gridFrame)
        self.comboBox_editor.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_editor.setStyleSheet("background: #fff;\n"
f"color:#000;\n"
"font: 8pt \"Arial\";\n"
"border-radius: 2px;\n"
"border: 0px;")
        self.comboBox_editor.setObjectName("comboBox")
        self.comboBox_editor.addItem(colors_editor[colors_num_editor][4])
        for key, value in colors_editor.items():
                if key != colors_num_editor:
                        self.comboBox_editor.addItem(value[4])
        self.gridLayout.addWidget(self.comboBox_editor, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridFrame)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit.setStyleSheet("background: #fff;\n"
f"color:#000;\n"
"font: 8pt \"Arial\";\n"
"border-radius: 2px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText(ip)
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame)
        self.label_3.setStyleSheet(f"color:{colors[colors_num][6]};\n"
"font: 63 12pt \\\"Yu Gothic UI Semibold\\\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridFrame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_2.setStyleSheet("background: #fff;\n"
f"color:#000;\n"
"font: 8pt \"Arial\";\n"
"border-radius: 2px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText(str(port))
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        self.label_2.setStyleSheet(f"color:{colors[colors_num][6]};\n"
"font: 63 12pt \\\"Yu Gothic UI Semibold\\\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        
        self.pushButtonDone = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f'border: 0px; border-radius: 5px; color:{colors[colors_num][6]}; font: 63 12pt "Yu Gothic UI Semibold";', self.frame)
        self.pushButtonDone.setMaximumSize(100, 30)
        self.pushButtonDone.setMinimumSize(100, 30)
        self.pushButtonDone.setText("Сохранить")

        self.gridLayout.addWidget(self.pushButtonDone, 4, 2, 1, 1)
        
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.gridFrame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.verticalFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тема Приложение"))
        self.label_4.setText(_translate("MainWindow", "Тема Редактора"))
        self.label_3.setText(_translate("MainWindow", "Порт Севрера"))
        self.label_2.setText(_translate("MainWindow", "IP Сервера"))
