# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addsolution.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from editor import Editor
from mysettings import getinfo
from PyQt5.Qsci import * 
from lexer import PyCustomLexer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, solution):
        colors_num = getinfo()[0]

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(40, 10, 40, 40)

        self.textEdit = Editor(self)
        self.textEdit.setText(solution)


        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};", self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Закрыть"))
