# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo
from PyQt5.Qsci import * 
from editor import Editor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, test):
        colors_num = getinfo()[0]
        with open(f"tests/{test}") as f:
                self.test = eval(f.read())

        MainWindow.setObjectName("MainWindow")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)

        #menu
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet(f"background-color: {colors[colors_num][5]};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton.setIcon(QtGui.QIcon(f"..\\pics\\mainpic{colors[colors_num][7]}.png"))
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet(f"background-color: {colors[colors_num][4]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.pushButton_back = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_back.setIcon(QtGui.QIcon(f"..\\pics\\returnpic{colors[colors_num][7]}.png"))
        self.pushButton_back.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_back.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setStyleSheet(f"background-color: {colors[colors_num][4]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.pushButton_back)

        self.horizontalLayout.addWidget(self.frame)


        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.textEdit = Editor(self)


        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalFrame = QtWidgets.QFrame(self.gridFrame)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.horizontalFrame)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser_2.setStyleSheet("background: #fff;\n"
f"border-radius: 3px; border-top:1px solid {colors[colors_num][3]}; font-size: 12px")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_2.addWidget(self.textBrowser_2)
        self.pushButton_2 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};", self.horizontalFrame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridFrame)
        self.textBrowser.setMaximumSize(QtCore.QSize(300, 16777215))
        self.textBrowser.setText(self.test["Description"])
        self.textBrowser.setStyleSheet(f"background-color: {colors[colors_num][5]};\n"
f"border-radius: 3px; color: {colors[colors_num][6]}; font-size: 12px")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridFrame)
        self.label.setObjectName("label")
        self.label.setStyleSheet(f'color:{colors[colors_num][6]};')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gridFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Проверить"))
        name = str(self.test['Name'])
        self.label.setText(_translate("MainWindow", f"<html><head/><body><p align=\"left\"><span style=\" font-size:12pt; font-weight:600;\">{name}</span></p></body></html>"))
