# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestsDone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, info):
        colors_num = getinfo()[0]

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 200)
        MainWindow.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.add_solution = True
        for i, right in enumerate(info[0]):
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setMinimumSize(QtCore.QSize(0, 0))
            self.label.setStyleSheet(f"color:{colors[colors_num][6]};")
            self.label.setMaximumSize(QtCore.QSize(16777215, 30))
            self.label.setObjectName("label")
            if right:
                self.label.setText(f"Тест{i+1} - Пройден")
            else:
                self.add_solution = False
                self.label.setText(f"Тест{i+1} - Непройден (Ввод: {info[1][i]}, Вывод: {info[2][i]})")
            self.verticalLayout.addWidget(self.label)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet(f"color:{colors[colors_num][6]};")
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        if info[2]:
            self.label.setText(f"Рандомные тесты - пройдены")
        else:
            self.add_solution = False
            self.label.setText(f"Рандомные тесты - Непройдены")
        self.verticalLayout.addWidget(self.label)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        if self.add_solution:
            self.pushButton_solution = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};", self.centralwidget)
            self.pushButton_solution.setMinimumSize(QtCore.QSize(30, 30))
            self.pushButton_solution.setIcon(QtGui.QIcon(f"..\\pics\\solution{colors[colors_num][7]}.png"))
            self.pushButton_solution.setIconSize(QtCore.QSize(25, 25))
            self.pushButton_solution.setMaximumSize(QtCore.QSize(30, 30))
            self.pushButton_solution.setObjectName("pushButton_solution")
            self.horizontalLayout.addWidget(self.pushButton_solution)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};", self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Закрыть"))
