# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lookTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo
from Funcs import connected


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, test):
        self.test = test
        self.connects = connected(test)
        colors_num = getinfo()[0]

        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        #menu
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet(f"background-color: {colors[colors_num][5]};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton.setIcon(QtGui.QIcon(f"pics\\info{colors[colors_num][7]}.png"))
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_2.setIcon(QtGui.QIcon(f"pics\\pen{colors[colors_num][7]}.png"))
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_3.setIcon(QtGui.QIcon(f"pics\\solution{colors[colors_num][7]}.png"))
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.pushButton_back = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_back.setIcon(QtGui.QIcon(f"pics\\returnpic{colors[colors_num][7]}.png"))
        self.pushButton_back.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_back.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.pushButton_back)

        self.horizontalLayout.addWidget(self.frame)

#tests
        frame_main = QtWidgets.QFrame()
        frame_main.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        layout_main = QtWidgets.QVBoxLayout()

        frame_main.setLayout(layout_main)

        self.label_main = QtWidgets.QLabel()
        self.label_main.setStyleSheet(f"color:{colors[colors_num][6]}")
        self.label_main.setObjectName("label")

        layout_main.addWidget(self.label_main)

        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setSpacing(20)
        self.gridLayout.setContentsMargins(17, 10, 15, 10)

        count = len(self.connects)
        self.Tests = []
        j = 0
        i = 0
        number = 0
        for i in range(count):
                number = i
                connect = self.connects[number]

                if j == 4:
                      break
                i = i % 8
                frame_3 = QtWidgets.QFrame()
                frame_3.setMinimumSize(QtCore.QSize(125, 200))
                frame_3.setMaximumSize(QtCore.QSize(125, 200))
                frame_3.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
        "border-radius: 5px;")
                frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                frame_3.setObjectName("frame_3")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(frame_3)
                self.verticalLayout_3.setObjectName("verticalLayout_2")

                if connect["done"]:
                        pixmap = QtGui.QPixmap('pics\\userdone.png')
                else:
                        pixmap = QtGui.QPixmap('pics\\usernotdone.png')

                label = QtWidgets.QLabel()
                label.setPixmap(pixmap)
                label.setAlignment(QtCore.Qt.AlignCenter)
                self.verticalLayout_3.addWidget(label)
                
                if number < count:
                        self.textBrowser_2 = QtWidgets.QTextBrowser()
                        self.textBrowser_2.setObjectName("textBrowser")
                        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
                        self.textBrowser_2.append(f"{connect['second_name']}\n{connect['first_name']}")
                        self.textBrowser_2.setStyleSheet(f'color:{colors[colors_num][6]}; font: 63 14px "Yu Gothic UI Semibold";')
                        self.verticalLayout_3.addWidget(self.textBrowser_2)
                
                self.gridLayout.addWidget(frame_3, j, 0 + i, 1, 1)

                if i % 7 == 0 and i != 0:
                      j += 1

                self.Tests.append(frame_3)

        if number < 6:
                spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.gridLayout.addItem(spacerItem1, j, i + 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, j + 1, 0, 1, 1)

        layout_main.addWidget(self.gridFrame)

        self.horizontalLayout.addWidget(frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_main.setText(_translate("MainWindow", f"<html><head/><body><p align=\"left\"><span style=\" font-size:12pt; font-weight:600;\">{self.test['Name']}</span></p></body></html>"))
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
