# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainTestCreate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, test):
        colors_num = getinfo()[0]

        MainWindow.setObjectName("MainWindow")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)


        #menu
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet(f"background-color: {colors[colors_num][5]};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][1]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton.setIcon(QtGui.QIcon(f"pics\\info{colors[colors_num][7]}.png"))
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_2.setIcon(QtGui.QIcon(f"pics\\testsintestpic{colors[colors_num][7]}.png"))
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_3.setIcon(QtGui.QIcon(f"pics\\random{colors[colors_num][7]}.png"))
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_info = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_info.setIcon(QtGui.QIcon(f"pics\\settingtest{colors[colors_num][7]}.png"))
        self.pushButton_info.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_info.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_info.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_info.setText("")
        self.pushButton_info.setObjectName("pushButton_info")
        self.verticalLayout.addWidget(self.pushButton_info)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.pushButton_delite = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_delite.setIcon(QtGui.QIcon(f"pics\\delite{colors[colors_num][7]}.png"))
        self.pushButton_delite.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_delite.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_delite.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_delite.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_delite.setText("")
        self.pushButton_delite.setObjectName("pushButton_delite")
        self.verticalLayout.addWidget(self.pushButton_delite)
        
        self.pushButton_back = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border: 0px; border-radius: 5px;", self.frame)
        self.pushButton_back.setIcon(QtGui.QIcon(f"pics\\returnpic{colors[colors_num][7]}.png"))
        self.pushButton_back.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_back.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_back.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border: 0px; border-radius: 5px")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.pushButton_back)

        self.horizontalLayout.addWidget(self.frame)


        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_4 = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};", self.gridFrame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridFrame)
        self.label.setStyleSheet(f"color:{colors[colors_num][6]}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        self.label_2.setStyleSheet(f"color:{colors[colors_num][6]}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridFrame)
        self.textEdit.setStyleSheet("background: #fff;\n"
"border: 0px;\n"
"border-radius: 2px;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setText(test.get("Description", ""))
        self.gridLayout.addWidget(self.textEdit, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)

        frame_7 = QtWidgets.QFrame()

        layout = QtWidgets.QHBoxLayout()
        layout.setObjectName("Center")
        layout.setAlignment(QtCore.Qt.AlignCenter)

        frame_7.setLayout(layout)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        layout.addItem(spacerItem2)

        frame_3 = MyFrame(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), "border-radius: 5px;", self.gridFrame)
        frame_3.setMinimumSize(QtCore.QSize(125, 200))
        frame_3.setMaximumSize(QtCore.QSize(125, 200))
        frame_3.setStyleSheet(f"background-color: {colors[colors_num][2]};\n"
"border-radius: 5px;")
        frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_2")

        pixmap = QtGui.QPixmap(f'testsimgs\\{test["iconame"]}.png')

        label = QtWidgets.QLabel()
        label.setPixmap(pixmap)
        label.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_3.addWidget(label)
        
        self.textBrowser_2 = QtWidgets.QTextEdit(frame_3)
        self.textBrowser_2.setObjectName("textBrowser")
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        for i in test["Name"].split("\n"):
            self.textBrowser_2.append(i)
        self.textBrowser_2.setStyleSheet(f'color:{colors[colors_num][6]}; font: 63 14px "Yu Gothic UI Semibold";')
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_3.addWidget(self.textBrowser_2)

        layout.addWidget(frame_3)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        layout.addItem(spacerItem2)

        self.gridLayout.addWidget(frame_7, 2, 1, 1, 1)

        self.horizontalLayout.addWidget(self.gridFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Далее"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Название</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Описание</span></p></body></html>"))
