# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuDownloadTests.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MyQtClasses import MyFrame, MyButton, MyTextBrowser
from colors import colors
from mysettings import getinfo
from Funcs import getInfoTests


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        colors_num = getinfo()[0]
        tests = getInfoTests()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(f"background-color: {colors[colors_num][3]};")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        with open("downloadtest.txt") as f:
            download = eval(f.read())

        self.checksboxes = []
        for i, test in enumerate(tests):
            checkBox = QtWidgets.QCheckBox(self.centralwidget)
            checkBox.setObjectName("checkBox")
            checkBox.setStyleSheet(f"color:{colors[colors_num][6]};\n"
    "font: 63 12pt \\\"Yu Gothic UI Semibold\\\";")
            checkBox.setText(test["Name"].replace("\n", ' '))
            if i in download:
                checkBox.setChecked(True)
            self.verticalLayout.addWidget(checkBox)
            self.checksboxes.append(checkBox)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = MyButton(QtGui.QColor(*colors[colors_num][0]), QtGui.QColor(*colors[colors_num][1]), f"border: 0px; border-radius: 5px;color:{colors[colors_num][6]};font: 63 10pt \\\"Yu Gothic UI Semibold\\\;", self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
